language: node_js
node_js: 10
services: postgresql
install:
  - npm install
before_script:
  - psql -c 'create database "pg-bump";' -U postgres
script:
  - npm run cover
after_script:
  - npm install -g codecov
  - codecov
