services:

  postgres:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - 5432:5432

  pgweb:
    image: sosedoff/pgweb:0.11.11
    environment:
      - DATABASE_URL=postgres://user:password@postgres/pg-bump?sslmode=disable
    ports:
      - 8081:8081
    depends_on:
      - postgres
    restart: always
