name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        include:
          - node-version: 18.x
            env:
              COVERAGE: 1
    steps:
      - name: Setup
        uses: actions/checkout@v3
      - name: Run on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Compile
        run: npm run build
      - name: Copy .env
        run: cp .env.example .env
      - name: Start Database
        run: docker-compose up --build -d
      - name: Run Tests
        run: npm run cover
      - name: Publish Coverage Report
        if: ${{ matrix.env.COVERAGE }}
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
